### ISSUE TITLE
Trying to build and run PMOS on my Xiaomi Nabu

### ISSUE THREAD

**Issue by ClearStaff** [map220v/postmarket_xiaomi_nabu#1]
Hi,
im trying to install PMOS on my Xiaomi Nabu, but i have encountered a few problems.

After downloading PKGBUILDs from this repository i tried to create rootfs with pmbootstrap install yet it quietly stuck on kernel building, i fixed that by updating commit in PKGBUILD to the latest available in kernel repository and fixing checksums (to one with sound nodes) and updating kernel config accordingly, building kernel now goes further yet it crashes on compiling DTB's without any reasonable output in pmbootstrap log, only that it crashed on kernel's Makefile: 1199 without any additional error output.

Can you update PKGBUILD and Kconfig of kernel package to latest local changes you've made in kernel repository, or provide any tips on how to compile these packages, maybe i am doing something wrong with Kconfig and it crashes....

Thank You for any moment spent on the issue

**Comment by map220v** [comment]
Should be fixed in last commit
