### ISSUE TITLE
ERROR: linux-postmarketos-qcom-sm8150-nabu: build failed

### ISSUE THREAD

**Issue by emretoprak** [map220v/postmarket_xiaomi_nabu#2]
Hi,

I Just try to build your repo. i have an error on 'pmbootstrap install' command. what am i missing?

`
>>> ERROR: linux-postmarketos-qcom-sm8150-nabu: build failed

(285702) [09:46:02] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

(285702) [09:46:02] NOTE: The failed command's output is above the ^^^ line in the log file: /home/emretoprak/.local/var/pmbootstrap/log.txt

(285702) [09:46:02] ERROR: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc HOME=/home/pmos abuild -D postmarketOS -d

RuntimeError: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc HOME=/home/pmos abuild -D postmarketOS -d

`

**Comment by map220v** [comment]
it's not full log, check full log using this command `cat ~/.local/var/pmbootstrap/log.txt`

**Comment by emretoprak** [comment]
full log attached.

[log.txt](https://github.com/map220v/postmarket_xiaomi_nabu/files/9488263/log.txt)


i think it's about line = '547'  No such file or directory but what file or directory i don't get it.

**Comment by emretoprak** [comment]
now i fix it

makedepends="bash gcc bison findutils flex installkernel openssl-dev perl postmarketos-installkernel"

i just add bash to makedepends now building is ok

**Comment by map220v** [comment]
yes, kernel 5.19 requires bash but pmbootstrap doesn't install it by default.
