### ISSUE TITLE
No battery state and charging support.

### ISSUE THREAD

**Issue by ClearStaff** [map220v/postmarket_xiaomi_nabu#3]
Hi. Ln8000 charger is not working on pmos currently on this device.
I have found driver in https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/nabu-r-oss/drivers/power/supply/ti

Should i try to port this to mainline kernel or you are already working on this?

**Comment by map220v** [comment]
Im currently working on another project for Mi Pad 5.
You can try to port ln8000 charger, but it's seems that this tablet also has bq25970 charger it has been already ported here `https://patchwork.kernel.org/project/linux-pm/patch/20201009144112.3007-2-dmurphy@ti.com/`
