### ISSUE TITLE
Upstreaming the device to pmaports

### ISSUE THREAD

**Issue by Newbytee** [map220v/postmarket_xiaomi_nabu#6]
Hello! :wave: 

Good job on the port! I was wondering, have you considered upstreaming these changes to pmaports and sm8150-mainline, respectively? It would make installing postmarketOS on this device easier for end users.

Thanks in advance.

**Comment by map220v** [comment]
Im currently not working on this project, serdeliuk works on pmos for nabu https://forum.xda-developers.com/t/rom-postmarketos-linux-boot-on-xiaomi-pad-5-nabu.4454143/post-87995271
